### ISSUE TITLE
很好用非常感谢，能否加上五笔自造词功能？

### ISSUE THREAD

**Issue by anacn** [SivanLaai/rime-pure#54]
类似wubi98版按 ` [精确造词] 的功能，自己折腾半天不会，求助大佬加上。

**Comment by SivanLaai** [comment]
五笔造词的功能其实比较简单，你直接把你要的词加到字典里面就可以，编码你可以网上查，然后加。

**Comment by SivanLaai** [comment]
```yaml
---
name: qq86wubi_user
version: "2019-01-20"
last_edit_time: "2019-02-28"

sort: original
# 码表的排序方式
  # by_weight 权重
  # original 原始顺序

#use_preset_vocabulary: true # 是否引入【八股文】的词频词序
...

# ----- 码表开始 -----
# 格式：字词 键码  权重 （中间是tab，不是空格）
# '#'开头的只是注释，所以可以随便分类了
# 注释只能另起一行写，不能在词条后面写

铁齿铜牙纪晓岚	qhqm #这里就是你要添加的五笔字典，然后每次添加完成后重新部署

```
