### ISSUE TITLE
一直有个困扰,怎么取消F4快捷键

### ISSUE THREAD

**Issue by tttfffyyy** [SivanLaai/rime-pure#70]
百度找到的方法都没有用

**Comment by SivanLaai** [comment]
打开```%Program%\Rime\weasel-0.14.3\data\default.yaml```，定位到：
```yaml
switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
```
修改为如下：
```yaml
switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
```
